# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# To run tests, the ruby files in lib must be loaded
require "capybara/rspec"
require "pry"

files = Dir["./lib/**/*.rb"]
files.each { |file| require file }

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Enables Capybara feature tests
  Capybara.app = URLShortener.new

  # Run specs in random order to surface order dependencies
  config.order = 'random'
end
